### ISSUE TITLE
[Scheduler] Rewrite Roadmap

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/SinbadCogs#146]
So, there are some unfun things with the current iteration of the scheduler. I'm looking at a full rewrite to properly support more things.

Here's the current list of things which aren't supported, but are planned to be supported.

- [ ] User default timezones.
- [ ] Commands retaining timezone awareness (automatic daylight savings time :eyes: )
- [ ] Snoozing things.
- [ ] Better management of scheduled events.
- [ ] Use of new things added in Red to support non-interactive use (ty Liz for that)
- [ ] Migrating events to a different timezone.
- [ ] Externally accessible API (documented and supported) for other cog use
- [ ] Event dispatches for other cog use

There's room for more in theory, and possibly an offering for this as a core scheduler cog later on if this reaches a level of both stability, accessibility, and feature strength along the way.

This is not an exhaustive list of what may be added either.

Some examples of things I'm currently considering supporting, but haven't decided on yet:

- [ ] events which run based on an ical entry
- [ ] running every [day of week/month] 
- [ ] running every nth [day of week]

While these are not currently a "yes" the current redesign will be capable of supporting them without much hassle to work with the other forms beyond additional parsing needs.

**Comment by mikeshardmind** [comment]
Superseded by work to move this into core Red
